I decided to treat this as a classification problem by creating a new binary variable affair
(did the woman have at least one affair?) and trying to predict the classification for each
woman.
Dataset
The dataset I chose is the affairs dataset that comes with Statsmodels. It was derived
from a survey of women in 1974 by Redbook magazine, in which married women were
asked about their participation in extramarital affairs. More information about the study
is available in a 1978 paper from the Journal of Political Economy.
Description of Variables
The dataset contains 6366 observations of 9 variables:
rate_marriage: woman's rating of her marriage (1 = very poor, 5 = very good)
age: woman's age
yrs_married: number of years married
children: number of children
religious: woman's rating of how religious she is (1 = not religious, 4 = strongly religious)
educ: level of education (9 = grade school, 12 = high school, 14 = some college, 16 =
college graduate, 17 = some graduate school, 20 = advanced degree)

occupation: woman's occupation (1 = student, 2 = farming/semi-skilled/unskilled, 3 =
"white collar", 4 = teacher/nurse/writer/technician/skilled, 5 = managerial/business, 6 =
professional with advanced degree)
occupation_husb: husband's occupation (same coding as above)
affairs: time spent in extra-marital affairs

In [2]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from patsy import dmatrices
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn import metrics
import warnings
from sklearn.cross_validation import cross_val_score

In [3]:
# load dataset
dta = sm.datasets.fair.load_pandas().data

# add "affair" column: 1 represents having affairs, 0 represents not
dta['affair'] = (dta.affairs > 0).astype(int)

In [4]:
dta.groupby('affair').mean()

rate_marriage        age  yrs_married  children  religious       educ  \
affair                                                                          
0            4.329701  28.390679     7.989335  1.238813   2.504521  14.322977   
1            3.647345  30.537019    11.152460  1.728933   2.261568  13.972236   

        occupation  occupation_husb   affairs  
affair                                         
0         3.405286         3.833758  0.000000  
1         3.463712         3.884559  2.187243

In [5]:
dta.groupby('rate_marriage').mean()

age  yrs_married  children  religious       educ  \
rate_marriage                                                           
1.0            33.823232    13.914141  2.308081   2.343434  13.848485   
2.0            30.471264    10.727011  1.735632   2.330460  13.864943   
3.0            30.008056    10.239174  1.638469   2.308157  14.001007   
4.0            28.856601     8.816905  1.369536   2.400981  14.144514   
5.0            28.574702     8.311662  1.252794   2.506334  14.399776   

               occupation  occupation_husb   affairs    affair  
rate_marriage                                                   
1.0              3.232323         3.838384  1.201671  0.747475  
2.0              3.327586         3.764368  1.615745  0.635057  
3.0              3.402820         3.798590  1.371281  0.550856  
4.0              3.420161         3.835861  0.674837  0.322926  
5.0              3.454918         3.892697  0.348174  0.181446

In [6]:
# create dataframes with an intercept column and dummy variables for
# occupation and occupation_husb
y, X = dmatrices('affair ~ rate_marriage + age + yrs_married + children + \
                  religious + educ + C(occupation) + C(occupation_husb)',
                  dta, return_type="dataframe")
print (X.columns)

Index(['Intercept', 'C(occupation)[T.2.0]', 'C(occupation)[T.3.0]',
       'C(occupation)[T.4.0]', 'C(occupation)[T.5.0]', 'C(occupation)[T.6.0]',
       'C(occupation_husb)[T.2.0]', 'C(occupation_husb)[T.3.0]',
       'C(occupation_husb)[T.4.0]', 'C(occupation_husb)[T.5.0]',
       'C(occupation_husb)[T.6.0]', 'rate_marriage', 'age', 'yrs_married',
       'children', 'religious', 'educ'],
      dtype='object')


In [7]:
# fix column names of X
X = X.rename(columns = {'C(occupation)[T.2.0]':'occ_2',
                        'C(occupation)[T.3.0]':'occ_3',
                        'C(occupation)[T.4.0]':'occ_4',
                        'C(occupation)[T.5.0]':'occ_5',
                        'C(occupation)[T.6.0]':'occ_6',
                        'C(occupation_husb)[T.2.0]':'occ_husb_2',
                        'C(occupation_husb)[T.3.0]':'occ_husb_3',
                        'C(occupation_husb)[T.4.0]':'occ_husb_4',
                        'C(occupation_husb)[T.5.0]':'occ_husb_5',
                        'C(occupation_husb)[T.6.0]':'occ_husb_6'})

In [8]:
# flatten y into a 1-D array
y = np.ravel(y)

In [9]:
# instantiate a logistic regression model, and fit with X and y
model = LogisticRegression()
model = model.fit(X, y)

# check the accuracy on the training set
model.score(X, y)           

0.7258875274897895

73% accuarcy seems good but what is the null error rate?

In [10]:
# what percentage had affairs?
y.mean()

0.3224945020420987

In [11]:
X.columns, np.transpose(model.coef_)  #examine the coeficients

(Index(['Intercept', 'occ_2', 'occ_3', 'occ_4', 'occ_5', 'occ_6', 'occ_husb_2',
        'occ_husb_3', 'occ_husb_4', 'occ_husb_5', 'occ_husb_6', 'rate_marriage',
        'age', 'yrs_married', 'children', 'religious', 'educ'],
       dtype='object'), array([[ 1.48983606],
        [ 0.1880664 ],
        [ 0.49894812],
        [ 0.25066814],
        [ 0.839008  ],
        [ 0.83390825],
        [ 0.19063622],
        [ 0.2978329 ],
        [ 0.16140914],
        [ 0.18777109],
        [ 0.19401647],
        [-0.70311973],
        [-0.05841813],
        [ 0.10567669],
        [ 0.01691983],
        [-0.37113512],
        [ 0.00401584]]))

In [12]:
#evaluate the model by splitting into train and test sets
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
model2 = LogisticRegression()
model2.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [13]:
# predict class labels for the test set
predicted = model2.predict(X_test)
print (predicted)

[1. 0. 0. ... 0. 0. 0.]


In [14]:
#generate class probabbilties
probs=model2.predict_proba(X_test)
print(probs)

[[0.35142488 0.64857512]
 [0.90952576 0.09047424]
 [0.72576603 0.27423397]
 ...
 [0.55736751 0.44263249]
 [0.81213933 0.18786067]
 [0.74729595 0.25270405]]


In [15]:
#generate evaluation metrics
print (metrics.accuracy_score(y_test, predicted))
print (metrics.roc_auc_score(y_test, predicted))


0.7298429319371728
0.6339179260634122


The accuracy is 73%, which is the same as we experienced when training and predicting on the same data.

We can also see the confusion matrix and a classification report with other metrics

In [16]:
print (metrics.confusion_matrix(y_test, predicted))
print (metrics.classification_report(y_test, predicted))

[[1169  134]
 [ 382  225]]
             precision    recall  f1-score   support

        0.0       0.75      0.90      0.82      1303
        1.0       0.63      0.37      0.47       607

avg / total       0.71      0.73      0.71      1910



In [17]:
#evaluate the model using 10-fold cross-validation
scores=cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=10)
print (scores)
print (scores.mean())

[0.72100313 0.70219436 0.73824451 0.70597484 0.70597484 0.72955975
 0.7327044  0.70440252 0.75157233 0.75      ]
0.7241630685514876


Still performing 73% accuracy.